import { Edit3, MapPin, Plus, ToggleLeft, ToggleRight } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Button, Field, Input, Modal, PageHeader, StatusBadge } from '../../components/ui'
import { useAdminCinemasQuery, useCreateCinemaMutation, useSetCinemaStatusMutation, useUpdateCinemaMutation } from '../../features/admin/hooks'
import type { Cinema } from '../../types'

type Form = { name: string; city: string; address: string; longitude: string; latitude: string }
const empty: Form = { name: '', city: '', address: '', longitude: '', latitude: '' }
function toForm(c: Cinema): Form { return { name:c.name, city:c.city, address:c.address, longitude:c.longitude ? String(c.longitude):'', latitude:c.latitude ? String(c.latitude):'' } }
export function CinemasAdminPage() {
  const query=useAdminCinemasQuery(), create=useCreateCinemaMutation(), update=useUpdateCinemaMutation(), status=useSetCinemaStatusMutation()
  const [open,setOpen]=useState(false),[editing,setEditing]=useState<Cinema|null>(null),[form,setForm]=useState<Form>(empty),[error,setError]=useState('')
  function openCreate(){setEditing(null);setForm(empty);setError('');setOpen(true)} function openEdit(c:Cinema){setEditing(c);setForm(toForm(c));setError('');setOpen(true)}
  async function submit(e:FormEvent){e.preventDefault();setError('');const data={...form,longitude:Number(form.longitude||0),latitude:Number(form.latitude||0)};try{if(editing)await update.mutateAsync({id:editing.id,data});else await create.mutateAsync(data);setOpen(false)}catch(cause){setError(cause instanceof Error?cause.message:'保存失败，请重试')}}
  return <div className="admin-page"><PageHeader eyebrow="PLATFORM" title="影院管理" description="维护 SaaS 租户影院，管理营业状态与基础地址信息。" actions={<Button onClick={openCreate}><Plus size={15}/>新增影院</Button>}/><div className="admin-table-card"><table className="admin-table"><thead><tr><th>影院</th><th>城市</th><th>地址</th><th>状态</th><th>操作</th></tr></thead><tbody>{(query.data??[]).map(c=><tr key={c.id}><td><div className="table-movie"><div className="hall-icon"><MapPin size={17}/></div><div><strong>{c.name}</strong><span>ID {c.id}</span></div></div></td><td>{c.city}</td><td>{c.address}</td><td><StatusBadge status={c.status||'ACTIVE'}/></td><td><div className="table-actions"><button onClick={()=>openEdit(c)} title="编辑"><Edit3 size={16}/></button><button onClick={()=>status.mutate({id:c.id,status:c.status==='ACTIVE'?'INACTIVE':'ACTIVE'})} title="切换状态">{c.status==='ACTIVE'?<ToggleRight size={18}/>:<ToggleLeft size={18}/>}</button></div></td></tr>)}</tbody></table></div><Modal open={open} title={editing?'编辑影院':'新增影院'} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}><Field label="影院名称"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><div className="form-grid"><Field label="城市"><Input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} required/></Field><Field label="地址"><Input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} required/></Field></div><div className="form-grid"><Field label="经度"><Input type="number" step="any" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></Field><Field label="纬度"><Input type="number" step="any" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/></Field></div>{error&&<div className="form-error">{error}</div>}<div className="modal-form-actions"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>取消</Button><Button type="submit" disabled={create.isPending||update.isPending}>{create.isPending||update.isPending?'保存中…':'保存影院'}</Button></div></form></Modal></div>
}
